apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: k8s-hablab-cluster
  region: eu-west-1

vpc:
  subnets:
    private:
      eu-west-1a: { id: subnet-000cbb77 }
      eu-west-1b: { id: subnet-706ade29 }

nodeGroups:
  - name: ng-1-workers
    labels: { role: workers }
    instanceType: t2.small
    desiredCapacity: 1
    privateNetworking: true
    tags:
      Environment: devaws
      Schedule: ASG-Managed
  - name: ng-2-builders
    labels: { role: builders }
    instanceType: t2.small
    desiredCapacity: 1
    privateNetworking: true
    iam:
      withAddonPolicies:
        imageBuilder: true
    tags:
      Environment: devaws
      Schedule: ASG-Managed